logo: "<img src='/assets/img/Rida_W.png' style='height: 48px; width: 48px;'/>" # add logo name
title: "Raditech Photography"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rida2000.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "Raditech Photography" # add banner title
banner-desc: "Beautiful things don't ask for attention." # add banner description

# Authors settings
authors:
  -
    abbv: "rida"
    name: "Rida"
    pic:  "rida.jpg"
    about: >
      00'<br/>
      Amateur photographer & videographer<br/>
      Base in Shanghai, China<br/>
      Major in Industrial Design<br/>
      Tongji University<br/>
    email: "rida2000@126.com"
    phone: "(021)-7355608"
    website: "https://rida2000.github.io"
  -
    abbv: "drew"
    name: "Drew"
    pic:  "drew.jpg"
    about: >
      Drew is a Chinese product designer and photographer living and working in Shanghai.
    email: "aca1224@foxmail.com"
    phone: "(021)-114514"
    website: "https://www.instagram.com/drewluvpalanuial/"
  -
    abbv: "lzp"
    name: "littleping"
    pic:  "face.jpg"
    about: >
      test
    email: "lzp@shu.edu.cn"
    phone: "(021)-114514"
    website: "https://steamcommunity.com/profiles/76561198422205047/"

# Author settings
# author-pic: face.jpg # your photo
# author-name: Rida
# about-author: "00' amateur photographer and videographer from Shanghai, China. Major in Industrial Design at Tongji University."
# email: "rida2000@126.com" # your email
# phone: "(496)-169-6557" # your pnone number
# website: "https://rida2000.github.io" # you website

# Social link
# google_url:    # add url link
# twitter_url:   # add url link
# instagram_url: # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
# facebook_url:  # add url link

# Disqus
discus_identifier: Rida2000 # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]